title: Vi's World
author: Vanessa :)
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Coding and hacking the mainframes, or whatever. I'm just here to have fun!! 

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username: viaod # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

# page theme 
theme: jekyll-theme-minimal
